backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "navbar"
    label: "Navbar"
    files:
      - file: "site/content/navbar.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Logo Image",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Menu Side", name: "linkSide", widget: "select", options: ["left", "right"] },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }

  - label: "Sections"
    name: "sections"
    files:
      - label: "Hero"
        name: "hero"
        file: "site/content/hero.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "hero" }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Image Description", name: "imageAlt", widget: "string" }

      - label: "About"
        name: "about"
        file: "site/content/about.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about" }
          - { label: Title, name: title, widget: string }
          - label: Sections
            name: sections
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: "Image Description", name: "imageAlt", widget: "string" }
              - { label: Content, name: content, widget: markdown }

      - label: "Find Us"
        name: "find-us"
        file: "site/content/find-us.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "find-us" }
          - { label: Title, name: title, widget: string }
          - { label: Address, name: address, widget: string }
          - {
              label: "Location",
              name: "location",
              widget: "object",
              fields:
                [
                  { label: "Latitude", name: "latitude", widget: "string" },
                  { label: "Longitude", name: "longitude", widget: "string" },
                ]
          }
          - { label: Phone, name: phone, widget: string }
          - label: Hours
            name: hours
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: From, name: from, widget: string }
              - { label: To, name: to, widget: string }

      - label: "Events"
        name: "events"
        file: "site/content/events.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "events" }
          - { label: Title, name: title, widget: string }
          - label: Events
            name: events
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: "Facebook link", name: "facebookLink", widget: "string" }
              - { label: "Event type", name: "type", widget: "select", options: ["recurring", "one time event"] }
              - { label: "Day of Week", name: "dayOfWeek", widget: "select", options: ["lun", "mar", "mer", "jeu", "ven", "sam", "dim"]  }
              - { label: "Day number", name: "dayNumber", widget: "string" }
              - { label: "Month", name: "month", widget: "string" }
              - { label: From, name: from, widget: string }
              - { label: To, name: to, widget: string }

      - label: "Image Gallery"
        name: "gallery"
        file: "site/content/gallery.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery" }
          - { label: Title, name: title, widget: string }
          - label: Images
            name: images
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: "Image Description", name: "imageAlt", widget: "string" }
